<a href="https://colab.research.google.com/github/rmfpafls/Udemy_lecture/blob/main/machine_learning/1_Data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# [Data Preprocessing Tools] - 데이터 전처리 과정

# 1. Importing the libaries

In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# 2. Importing the dataset

In [8]:
# 새로운 변수 생성하고 데이터 세트 할당하기
dataset = pd.read_csv("/content/drive/MyDrive/udemy_머신러닝/Data.csv")

# 특성행렬과 종속변수 행렬 만들기
# 특성 열을 사용해 종속 변수를 예측하는 것
# 보통 앞부분의 열에 특성을 배치하고, 마지막 열에 종속 변수를 배치한다.
X = dataset.iloc[:, :-1].values
#iloc : 인덱스로 원하는 값을 찾는다.
# : 처음부터 마지막 열중에 마지막 열 제외하고 X에 할당
# .values : 값을 가지고 오겠다.
y =  dataset.iloc[:, -1].values

In [9]:
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [10]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [11]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# 3. Taking care of missing data
-결측치 처리하는 방법


1. 결측치를 열의 평균으로 대체하는 방법

In [12]:
# 데이터 셋의 결측치의 갯수를 세는 방법
missing_data = dataset.isnull().sum()
print(missing_data)

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64


In [13]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
# 결측치가 nan인 값에다가, strategy가 평균인 값을 넣겠다.
imputer.fit(X[:, 1:3])
# fit메서드를 사용하여 imputer를 특성 행렬에 적용할 수 있다.

# 첫번째열은 행의 이름을 담고 있으므로 첫번째열을 제외해야된다.
# transform 매서드를 사용해서 값을 대체할 수 있다.
X[:, 1:3] = imputer.transform(X[:, 1:3])
# transform : 학습된 변환을 다른 데이터에 적용한다.

In [14]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# 4. Encoding categorical data
- 범주형 데이터 인코딩
: 첫번째 열이 나라이름으로 문자열로 되어 있으니까 이걸 숫자로 할당하는 거임

-  이게 바로 **'원핫-인코딩'**임



In [23]:
# 4-1 Encodeing the independent variable

## 원-핫 인코딩하기
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(),[0])], remainder = 'passthrough')
# 1. 환 유형인 인코딩, 2. 원핫인코딩, 3. 열의 인덱스
# remainder : CoulmnTransformer에서 변환하지 않은 나머지 열들을어떻게 처리할지를 결정하는 매개변수
# passthough : 변환을 적용하지 않은 나머지 열들을 그대로 유지하여 결과에 포함한다.
# drop : 변환되지 않은 나머지 열들을 결과에서 제외한다.
# custom transformer : 사용자가 정의한 변환으로 적용한다.

#ct.fit_transform(X)
# fit_transform() 매서드는 넘파이 배열을 반환하지 않는데,
# 머신러닝은 넘파이 배열로 넘겨줘야된다.

X = np.array(ct.fit_transform(X))
# fit_transform : 데이터를 학습하고 바로 변환하는 기능.
print(X)
# 출력해서 0과 1이 아닌 항은 원래 항임.

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [24]:
# Encoding the Dependent Variable
# 종속 변수 인코딩
# 종속 변수 : 예측하려고 하는 대상 변수,
# 보통 결과나 목표 변수라고도 불리며, 독립변수에 의해 영향을 받음
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y) # 맨 마지막 열('NO', 'Yes')를 숫자로 바꿈
print(y)

[0 1 0 0 1 1 0 1 0 1]


# 5. Splitting the dataset into the Training set and Test set

- 왜 나눌까?

: 단순히 테스트 세트가 머신러닝 모델을 평가하기 위한 완전히 새로운 모델이어야하기 때문에.

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)
# X, y, 분할비, random_state = 1 : random_state에 특정 정수 값으로 설정하면,
# 해당 값을 기반으로 데이터가 분할되어 항상 같은 방식으로 훈련 및 테스트 셋이 만들어진다.


In [26]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [27]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [28]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [29]:
print(y_test)

[0 1]


In [ ]:
## 실습
# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
# Load the Iris dataset
dataset = pd.read_csv("iris.csv")
# Separate features and target
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
# Split the dataset into an 80-20 training-test set
X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size = 0.2, random_state = 42)
# Apply feature scaling on the training and test sets
print(X_train)
print(X_test)
print(y_train)
print(y_test)
# Print the scaled training and test sets
scaler = StandardScaler()
scaler.fit_transform(X_train)
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print(X_train)
print(X_test)

# 6. Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
